name: Synchronize Repositories

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  milestone:
    name: Synchronize Repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/install/git.sh)
      - name: Synchronize ORY Hydra
        run: ./scripts/sync-server.sh ory/hydra master Hydra
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Synchronize ORY Keto
        run: ./scripts/sync-server.sh ory/hydra master Keto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Synchronize ORY Oathkeeper
        run: ./scripts/sync-server.sh ory/hydra master Oathkeeper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Synchronize ORY Kratos
        run: ./scripts/sync-server.sh ory/hydra master Kratos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Synchronize ORY Hydra Login, Logout And Consent Node Example
        run: ./scripts/sync-library.sh ory/hydra-login-consent-node master "Hydra Login, Logout And Consent Node Example"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Synchronize ORY Kratos SelfService UI Node Example
        run: ./scripts/sync-library.sh ory/kratos-selfservice-ui-node master "Kratos SelfService UI Node Example"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Synchronize ORY Fosite
        run: ./scripts/sync-library.sh ory/fosite master Fosite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Synchronize ORY Dockertest
        run: ./scripts/sync-library.sh ory/dockertest v3 Dockertest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Synchronize ORY Herodot
        run: ./scripts/sync-library.sh ory/herodot master Herodot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Synchronize ORY Graceful
        run: ./scripts/sync-library.sh ory/graceful master Graceful
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Synchronize ORY Kubernetes Resources
        run: ./scripts/sync-library.sh ory/k8s master "Kubernetes Resources"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Synchronize ORY X
        run: ./scripts/sync-library.sh ory/x master X

